# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.1.1
source:
  sha256: 51d2af72279913b5d4cab1fe1f38b944cf70904c88bee246b5bd575844e7035a
  url: https://curl.se/download/curl-8.1.1.tar.bz2
build:
  number: 1
  run_exports:
    - libcurl >=8.1.1,<9.0a0
  string: h251f7ec_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - c-ares 1.19.0 h5eee18b_0
    - ca-certificates 2023.05.30 h06a4308_0
    - krb5 1.20.1 h143b758_1
    - libedit 3.1.20221030 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.52.0 h2d74bed_1
    - libssh2 1.10.0 hdbd6064_2
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.8 h7f8727e_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - krb5 >=1.20.1,<1.21.0a0
    - libgcc-ng >=11.2.0
    - libnghttp2 >=1.52.0
    - libnghttp2 >=1.52.0,<2.0a0
    - libssh2 >=1.10.0
    - libssh2 >=1.10.0,<2.0a0
    - openssl >=3.0.8,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 977a99c4-cbde-4219-a3e5-f5458d069385
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: 9464c506c114549efefe72a1fb4e70307cba21ae
