# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Jul 13 17:38:03 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.5.2
source:
  sha256: c82ab703f1784cd1ffa4cfad5fe80f1e994b9b7a612e9268ddd136c5ad19188e
  url: https://github.com/conda/conda/archive/23.5.2.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /croot/conda_1689269889729/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /croot/conda_1689269889729/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m conda init --install
  string: py311h06a4308_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.19.0 h5eee18b_0
    - ca-certificates 2023.05.30 h06a4308_0
    - curl 7.88.1 h5eee18b_1
    - expat 2.4.9 h6a678d5_0
    - gdbm 1.18 hd4cb3f1_4
    - gettext 0.21.0 h39681ba_1
    - git 2.40.1 pl5340h36fbf9e_1
    - icu 58.2 he6710b0_3
    - krb5 1.20.1 h143b758_1
    - libcurl 7.88.1 h251f7ec_1
    - libedit 3.1.20221030 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.52.0 h2d74bed_1
    - libssh2 1.10.0 hdbd6064_2
    - libstdcxx-ng 11.2.0 h1234567_1
    - libxml2 2.10.3 hcbfbd50_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.9 h7f8727e_0
    - pcre2 10.42 hebb0a14_0
    - perl 5.34.0 h5eee18b_2
    - readline 8.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.05.30 h06a4308_0
    - editables 0.3 py311h06a4308_0
    - hatch-vcs 0.2.0 py311h06a4308_0
    - hatchling 1.12.2 py311h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.9 h7f8727e_0
    - packaging 23.0 py311h06a4308_0
    - pathspec 0.10.3 py311h06a4308_0
    - pip 23.1.2 py311h06a4308_0
    - pluggy 1.0.0 py311h06a4308_1
    - python 3.11.4 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - ruamel.yaml 0.17.21 py311h5eee18b_0
    - setuptools 67.8.0 py311h06a4308_0
    - setuptools-scm 7.1.0 py311h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tqdm 4.65.0 py311h92b7b1e_0
    - typing-extensions 4.6.3 py311h06a4308_0
    - typing_extensions 4.6.3 py311h06a4308_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.38.4 py311h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - boltons >=23.0.0
    - conda-package-handling >=1.3.0
    - jsonpatch >=1.32
    - packaging >=23.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.11,<3.12.0a0
    - requests >=2.20.1,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=31.0.1
    - toolz >=0.8.1
    - tqdm >=4
  run_constrained:
    - conda-build >=3.18.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0
    - cytoolz >=0.8.1
test:
  downstreams: null
  imports:
    - conda
    - conda_env
  requires: null
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0228c089-92c9-48e6-8d36-a75857cb1a1c
  remote_url: git@github.com:AnacondaRecipes/conda-feedstock.git
  sha: 739adc610c12e9ca390e64a06ec109f17fb574b1
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
