# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /work/aggregate/conda-content-trust-feedstock/recipe, last modified Mon Feb 13 19:12:17 2023
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.1.3
source:
  fn: conda-content-trust-0.1.3.tar.gz
  sha256: 50a2732dcf3612bdff2b36171e3ebc72a74bbc258543a5aa2618218406b30a0d
  url: https://github.com/conda/conda-content-trust/archive/0.1.3.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '0'
  script: /work/ci_py311/conda-content-trust_1676851327497/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install --no-deps --ignore-installed -vv .
  string: py311h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py311h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - pip 22.3.1 py311h06a4308_0
    - python 3.11.0 h7a1cb2a_2
    - readline 8.2 h5eee18b_0
    - setuptools 65.5.0 py311h06a4308_0
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - cryptography
    - python >=3.11,<3.12.0a0
    - six
test:
  commands:
    - pip check
    - pytest -v tests
    - conda-content-trust --help
  imports:
    - conda_content_trust
  requires:
    - pip
    - pytest
    - pytest-cov
    - ruamel_yaml
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.rst
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
