# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu May 25 13:01:07 2023
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.8.0
source:
  sha256: 5e5212153e285a48223c70ede741d00304725a11cb690c494464a12f04c607f5
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.8.0.tar.gz
build:
  number: '0'
  script: /croot/conda-package-streaming_1685019673878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install --no-deps --no-build-isolation . -vv
  string: py311h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - flit-core 3.8.0 py311h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - pip 23.0.1 py311h06a4308_0
    - python 3.11.3 h7a1cb2a_0
    - readline 8.2 h5eee18b_0
    - setuptools 66.0.0 py311h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.38.4 py311h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.11,<3.12.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  description: 'An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.

    '
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 790377b5-b806-4ad7-ad0d-71f9cf0b588f
  recipe-maintainers:
    - dholth
  remote_url: git@github.com:AnacondaRecipes/conda-package-streaming-feedstock.git
  sha: c97bb0d2ca70ce821af058e1d681f2602a352ce5
