# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /work/aggregate/pluggy-feedstock/recipe, last modified Mon Feb 13 19:13:05 2023
# ------------------------------------------------

package:
  name: pluggy
  version: 1.0.0
source:
  fn: pluggy-1.0.0.tar.gz
  sha256: 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.0.0.tar.gz
build:
  number: '1'
  script: python -m pip install . --no-deps --ignore-installed
  string: py311h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py311h06a4308_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - packaging 22.0 py311h06a4308_0
    - pip 22.3.1 py311h06a4308_0
    - python 3.11.0 h7a1cb2a_2
    - readline 8.2 h5eee18b_0
    - setuptools 65.5.0 py311h06a4308_0
    - setuptools-scm 7.0.4 py311h06a4308_0
    - setuptools_scm 7.0.4 h06a4308_0
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tomli 2.0.1 py311h06a4308_0
    - typing-extensions 4.4.0 py311h06a4308_0
    - typing_extensions 4.4.0 py311h06a4308_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.11,<3.12.0a0
test:
  command:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io/en/latest/
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
